# - Find HTSLIB (includes and library)
# This module defines
#  HTSLIB_INCLUDE_DIR
#  HTSLIB_LIBRARIES
#  HTSLIB_FOUND
# also defined, but not for general use are
#  HTSLIB_LIBRARY, where to find the library.

if (NOT "$ENV{HTSLIB_ROOT}" STREQUAL "")
  SET(HTSLIB_CUSTOM_PATH $ENV{HTSLIB_ROOT})
endif()

FIND_PATH(HTSLIB_INCLUDE_DIR htslib/bgzf.h
/usr/include/
/usr/local/include/
/include
${HTSLIB_CUSTOM_PATH}/include
)

SET(HTSLIB_NAMES ${HTSLIB_NAMES} hts)
FIND_LIBRARY(HTSLIB_LIBRARY
  NAMES ${HTSLIB_NAMES}
  PATHS /usr/lib /usr/local/lib /lib /usr/lib/htslib /usr/local/lib/htslib /lib/htslib ${HTSLIB_CUSTOM_PATH}/lib
  )

IF (HTSLIB_LIBRARY AND HTSLIB_INCLUDE_DIR)
    SET(HTSLIB_LIBRARIES ${HTSLIB_LIBRARY})
    SET(HTSLIB_FOUND "YES")
ELSE (HTSLIB_LIBRARY AND HTSLIB_INCLUDE_DIR)
  SET(HTSLIB_FOUND "NO")
ENDIF (HTSLIB_LIBRARY AND HTSLIB_INCLUDE_DIR)


IF (HTSLIB_FOUND)
   IF (NOT HTSLIB_FIND_QUIETLY)
      MESSAGE(STATUS "Found a HTSLIB library: ${HTSLIB_LIBRARIES}")
   ENDIF (NOT HTSLIB_FIND_QUIETLY)
ELSE (HTSLIB_FOUND)
   IF (HTSLIB_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find a HTSLIB library")
   ENDIF (HTSLIB_FIND_REQUIRED)
ENDIF (HTSLIB_FOUND)

# Deprecated declarations.
SET (NATIVE_HTSLIB_INCLUDE_PATH ${HTSLIB_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_HTSLIB_LIB_PATH ${HTSLIB_LIBRARY} PATH)

MARK_AS_ADVANCED(
  HTSLIB_LIBRARY
  HTSLIB_INCLUDE_DIR
  )
