version: 2
jobs:
  build:
    docker:
      - image: bschiffthaler/seidr-build
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Out of src build
          command: mkdir build 
      - run:
          name: Cmake config
          command: cmake ..
          working_directory: build
      - run:
          name: Make
          command: make    
          working_directory: build
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - devel
    jobs:
      - build