{% set version = "0.14" %}

{% set build = 0 %}

{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
{% set build = build + 100 %}
{% endif %}



package:
  name: seidr
  version: {{ version }}

source:
   path: ../
#  git_rev: 0.13.1
#  git_url: https://github.com/bschiffthaler/seidr.git

build:
  number: {{ build }}

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - armadillo=*=*openblas*
    - boost
    - zlib
    - coin-or-clp
    - tbb-devel
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - armadillo=*=*openblas*
    - boost
    - zlib
    - coin-or-clp
    - tbb
    - {{ mpi }}  # [mpi != 'nompi']

about:
  home: https://github.com/bschiffthaler/seidr
  license: GPL-2.0-or-later
  license_file: LICENCE
  summary: Community gene network inference and exploration toolkit

test:
  commands:
    - seidr version 
    - anoverence -V 
    - correlation -V 
    - el-ensemble -V # [mpi == 'nompi']
    - el-ensemble -V # [mpi != 'nompi']
    - genie3 -V # [mpi == 'nompi']
    - genie3 -V # [mpi != 'nompi']
    - llr-ensemble -V # [mpi == 'nompi']
    - llr-ensemble -V # [mpi != 'nompi']
    - mi -V # [mpi == 'nompi']
    - mi -V # [mpi != 'nompi']
    - narromi -V # [mpi == 'nompi']
    - narromi -V # [mpi != 'nompi']
    - pcor -V 
    - plsnet -V # [mpi == 'nompi']
    - plsnet -V # [mpi != 'nompi']
    - svm-ensemble -V # [mpi == 'nompi']
    - svm-ensemble -V # [mpi != 'nompi']
    - tigress -V # [mpi == 'nompi']
    - tigress -V # [mpi != 'nompi']
    - tomsimilarity -V 
