package:
  name: seidr
  version: 0.13.1

source:
   path: ../
#  git_rev: 0.13.1
#  git_url: https://github.com/bschiffthaler/seidr.git

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - armadillo=*=*openblas*
    - boost
    - zlib
    - coin-or-clp
    - tbb-devel
  run:
    - armadillo=*=*openblas*
    - boost
    - zlib
    - coin-or-clp
    - tbb

about:
  home: https://github.com/bschiffthaler/seidr
  license: GPL-3
  summary: Community gene network inference and exploration toolkit
