# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SeidrFile__ptr <- function(p) {
    .Call(`_SeidRFile_SeidrFile__ptr`, p)
}

SeidrFileHeader__ptr <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr`, xp)
}

SeidrFileHeader__ptr__getAttr <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getAttr`, xp)
}

SeidrFileHeader__ptr__Position <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__Position`, xp)
}

SeidrFileHeader__ptr__getNodes <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getNodes`, xp)
}

SeidrFileHeader__ptr__getAlgs <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getAlgs`, xp)
}

SeidrFileHeader__ptr__getSTags <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getSTags`, xp)
}

SeidrFileHeader__ptr__getPageRank <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getPageRank`, xp)
}

SeidrFileHeader__ptr__getCloseness <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getCloseness`, xp)
}

SeidrFileHeader__ptr__getBetweenness <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getBetweenness`, xp)
}

SeidrFileHeader__ptr__getStrength <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getStrength`, xp)
}

SeidrFileHeader__ptr__getEigenvector <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getEigenvector`, xp)
}

SeidrFileHeader__ptr__getKatz <- function(xp) {
    .Call(`_SeidRFile_SeidrFileHeader__ptr__getKatz`, xp)
}

SeidrFile__ptr__vectorizeSF <- function(xpf, xph, scores, ranks, flags, supp_str, supp_int, supp_flt, indices, chunksize) {
    .Call(`_SeidRFile_SeidrFile__ptr__vectorizeSF`, xpf, xph, scores, ranks, flags, supp_str, supp_int, supp_flt, indices, chunksize)
}

SeidrFile__ptr__vectorizeSingle <- function(xpf, xph, score, rank, indices, index, chunksize) {
    .Call(`_SeidRFile_SeidrFile__ptr__vectorizeSingle`, xpf, xph, score, rank, indices, index, chunksize)
}

SeidrFile__ptr__close <- function(xpf) {
    invisible(.Call(`_SeidRFile_SeidrFile__ptr__close`, xpf))
}

SeidrFile__ptr__isopen <- function(xpf) {
    .Call(`_SeidRFile_SeidrFile__ptr__isopen`, xpf)
}

